---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [license]
#####################################################################################################################

# master

- name: "Configure server.conf [license] - master_uri state=present (dynamic)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=license
            option=master_uri
            value="https://{{ groups['licensemaster'][0] }}:8089"
            state=present
  when: splunk_server_conf.license.master_uri is defined and
        splunk_server_conf.license.master_uri == "dynamic"
  notify: splunk restart

- name: "Configure server.conf [license] - master_uri state=present (static)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=license
            option=master_uri
            value="{{ splunk_server_conf.license.master_uri }}"
            state=present
  when: splunk_server_conf.license.master_uri is defined and
        splunk_server_conf.license.master_uri != "dynamic"
  notify: splunk restart

- name: "Configure server.conf [license] - master_uri state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=license
            option=master_uri
            state=absent
  when: splunk_server_conf.license.master_uri is undefined
  notify: splunk restart
