---
- hosts: repository

  vars_prompt:
    - name: "app_name"
      prompt: "\n1) Repository directory name or git repo name (mandatory)\n   --> Repository location is defined in 'group_vars/all/splunk_repository'\n   (Example: TA-my-app or Splunk_TA-xxx)\n   Your answer"
      private: no

    - name: "app2group"
      prompt: "\n2) Target group (mandatory)\n   (Example: heavyforwarder)\n   Your answer"
      private: no

    - name: "filename"
      prompt: "\n3) Repository full filename (optional)\n   (Example: splunk-addon-xxx-v1.2.tgz) Leave empty if you want to use git\n   Your answer"
      private: no

    - name: "git_url"
      prompt: "\n4) Change git base URL (optional)\n   leave empty if you want to use default or if you want to use local file\n   --> default defined in: group_vars/all/splunk_repository\n   Your answer"
      private: no

    - name: "git_branch"
      prompt: "\n5) git branch (optional)\n   leave empty for default and if you want to use local file\n   Your answer"
      private: no
      default: "master"

  pre_tasks:
    - include_vars: inventories/{{ target_env }}/group_vars/all/splunk_repository
    - include_vars: inventories/{{ target_env }}/group_vars/{{ app2group }}/deployment

  tasks:
  - name: Check user input
    fail: msg="A required value is empty. Please restart playbook and ensure all mandatory fields are defined."
    when: app2group is not defined or app_name is not defined

  - name: Convert to ansible friendly name
    set_fact:
        app_variable: "{{ app_name | regex_replace('-', '_')}}"

  - name: Copy template app template
    command: cp -RfT roles/apps/app.template roles/apps/{{ app_name }} 

  - name: Set app variables
    template: src=roles/apps/{{ app_name }}/vars/main.yml.j2
              dest=roles/apps/{{ app_name }}/vars/main.yml
              mode=0640

  - name: Set app variables within group_vars
    template: src=roles/common/templates/add_app_groupvars.j2
              dest=inventories/{{ target_env }}/group_vars/{{ app2group }}/{{ app_name }}
              mode=0640

  - name: Remove template file
    file: path=roles/apps/{{ app_name }}/vars/main.yml.j2
          state=absent
 
  - name: Find app roles
    command: "ls roles/apps"
    register: app_roles

  - name: Create ae_deploy_apps.yml
    template: src=roles/common/templates/deploy_apps.yml.j2
              dest=./ae_deploy_apps.yml
              mode=0640

