- name: Configure splunk searchheads
  hosts: 
        - searchhead
        - activeinput
  user: ansible
  become: yes
  become_user: root

  roles:
    - group/searchhead
    - conf/web
    - conf/outputs
    - conf/server
