- name: Install open-vm-tools on all hosts
  hosts: "*:!repository"
  remote_user: ansible
  become: yes
  become_user: root

  # http://mirror.centos.org/centos-7/7/os/x86_64/Packages/

  roles:
    - openvmtools
