---
- hosts: repository

  tasks:
  - name: Find app roles (filter a subset)
    shell: "ls -1 roles/apps | egrep '({{ deploy_sub_apps }})'" 
    register: app_roles
    when: deploy_type == "custom" and deploy_sub_apps is defined

  - name: Create ae_deploy_apps.yml
    template: src=roles/common/templates/ae_deploy_apps_{{ target_env  }}.yml.j2
              dest=inventories/{{ target_env }}/ae_deploy_apps.yml
              mode=0640
    when: deploy_type == "custom" and deploy_sub_apps is defined and app_roles.stdout_lines is defined

  - name: Find app roles (no filtering)
    shell: "ls -1 roles/apps"
    register: app_roles
    when: deploy_type == "all"

  - name: Create ae_deploy_apps.yml
    template: src=roles/common/templates/ae_deploy_apps_{{ target_env  }}.yml.j2
              dest=inventories/{{ target_env }}/ae_deploy_apps.yml
              mode=0640
    when: deploy_type == "all" and app_roles.stdout_lines is defined


