- name: Format new disk storage
  hosts: "{{ server_hostname }}*"
  gather_facts: False

  tasks:
    - name: Power on if needed
      debug: msg="Please be patient as we wait until the VM is fully booted!"

    - name: Power on {{ server_hostname }}
      connection: local
      vmware_guest:
        hostname: '{{ vsphere.host[vsphere_var].dest }}'
        username: '{{ vsphere.host[vsphere_var].user }}'
        password: '{{ vsphere.host[vsphere_var].password }}'
        validate_certs: "{{ vsphere.host[vsphere_var].validate_certs }}"
        name: '{{ server_hostname }}'
        esxi_hostname: "{{ vsphere_esx_host }}"
        state: poweredon
        wait_for_ip_address: true

    - name: partitioning {{ server_disk_dev }}
      remote_user: ansible
      become: yes
      parted: 
        device: "{{ server_disk_dev }}" 
        number: 1
        flags: [ lvm ]
        label: gpt
        state: present
      when: server_scnd_disk is defined and server_disk_dev is defined 
   
    - name: create new lvm volgroup {{ server_lvm_vg }} with {{ server_disk_dev }}1
      remote_user: ansible
      become: yes
      lvg:
        vg: "{{ server_lvm_vg }}"
        pvs: "{{ server_disk_dev }}1"
      when: server_scnd_disk is defined and server_disk_dev is defined

    - name: create {{ server_lvm_lv }} logical volume in {{ server_lvm_vg }}
      remote_user: ansible
      become: yes
      lvol:
        vg: "{{ server_lvm_vg }}"
        lv: "{{ server_lvm_lv }}"
        size: 100%FREE
      when: server_scnd_disk is defined and server_disk_dev is defined

    - name: format /dev/mapper/{{ server_lvm_vg }}-{{ server_lvm_lv }} with {{ server_disk_fs }}
      remote_user: ansible
      become: yes
      filesystem:
        fstype: "{{ server_disk_fs }}"
        dev: "/dev/mapper/{{ server_lvm_vg }}-{{ server_lvm_lv }}"
      when: server_scnd_disk is defined and server_disk_dev is defined
   
    - name: add {{ server_disk_mountpoint }} to fstab
      remote_user: ansible
      become: yes
      mount:
        src: "/dev/mapper/{{ server_lvm_vg }}-{{ server_lvm_lv }}"
        path: "{{ server_disk_mountpoint }}"
        opts: "{{ server_disk_mountopts }}"
        fstype: "{{ server_disk_fs }}"
        backup: yes
        state: present
      when: server_scnd_disk is defined and server_disk_dev is defined

    - name: create mountpoint {{ server_disk_mountpoint }} 
      remote_user: ansible
      become: yes
      file:
        path: "{{ server_disk_mountpoint }}"
        mode: '0755'
        state: directory
      when: server_scnd_disk is defined and server_disk_dev is defined
