---

- name: Remove app
  file: path="{{ splunk_installation.splunk_home_path }}/etc/{{ item.key | replace('shcluster_apps', 'shcluster/apps') | replace('_', '-') }}/{{ app_name }}"
        state=absent
  when: item.value.delete == true
  with_dict: "{{ vars[app_variable] }}"
