---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [replication_port:<port>]
#####################################################################################################################

- name: "Configure server.conf [replication_port:<port>] - replication_port state=present"
  ini_file: dest="{{ splunk_conf_path }}/server.conf"
            section="replication_port://{{ splunk_server_conf.replication_port.port }}"
            state=present
  when: splunk_server_conf.replication_port is defined and
        splunk_server_conf.replication_port.disabled == "false" and
        splunk_server_conf.replication_port.port is defined
  notify: splunk restart

- name: "Configure server.conf [replication_port:<port>] - replication_port check presence"
  shell: grep 'replication_port:' {{ splunk_conf_path }}/server.conf | sed 's/\[replication_port:\/\/\(.*\)\]/\1/'
  register: splunk_server_replication_port_port_inifile
  changed_when: false
  notify: splunk restart

- name: "Configure server.conf [replication_port:<port>] - replication_port state=absent (default)"
  ini_file: dest="{{ splunk_conf_path }}/server.conf"
            section="replication_port://{{ splunk_server_replication_port_port_inifile.stdout }}"
            state=absent
  when: splunk_server_conf.replication_port is undefined or
        (splunk_server_conf.replication_port.disabled == "true" and
        splunk_server_conf.replication_port.port is undefined and
        splunk_server_replication_port_port_inifile is defined and
        splunk_server_replication_port_port_inifile.stdout != "")
  notify: splunk restart
