---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [shclustering]
#####################################################################################################################

# election

- name: "Configure server.conf [shclustering] - election state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=election
            value={{ splunk_server_conf.shclustering.election }}
            state=present
  when: splunk_server_conf.shclustering.election is defined
  notify: splunk restart

- name: "Configure server.conf [shclustering] - election state=absent"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=election
            state=absent
  when: splunk_server_conf.shclustering.election is undefined
  notify: splunk restart
