---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [shclustering]
#####################################################################################################################

# mgmt_uri

- name: "Configure server.conf [shclustering] - mgmt_uri state=present (dynamic)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=mgmt_uri
            value="https://{{ inventory_hostname }}:8089"
            state=present
  when: splunk_server_conf.shclustering.mgmt_uri is defined and
        splunk_server_conf.shclustering.mgmt_uri == "dynamic"
  notify: splunk restart

- name: "Configure server.conf [shclustering] - mgmt_uri state=present (static)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=mgmt_uri
            value={{ splunk_server_conf.shclustering.mgmt_uri }}
            state=present
  when: splunk_server_conf.shclustering.mgmt_uri is defined and
        splunk_server_conf.shclustering.mgmt_uri != "dynamic"
  notify: splunk restart

- name: "Configure server.conf [shclustering] - mgmt_uri state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=master_uri
            state=absent
  when: splunk_server_conf.shclustering.mgmt_uri is undefined
  notify: splunk restart
