---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [shclustering]
#####################################################################################################################

# replication_factor

- name: "Configure server.conf [shclustering] - replication_factor state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=replication_factor
            value={{ splunk_server_conf.shclustering.replication_factor }}
            state=present
  when: splunk_server_conf.shclustering.disabled == "false" and
        (splunk_server_conf.shclustering.replication_factor is defined or
        splunk_server_conf.shclustering.replication_factor != 3)
  notify: splunk restart

- name: "Configure server.conf [shclustering] - replication_factor state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=replication_factor
            state=absent
  when: splunk_server_conf.shclustering.disabled == "true" and
        (splunk_server_conf.shclustering.replication_factor is undefined or
        splunk_server_conf.shclustering.replication_factor == 3)
  notify: splunk restart
