---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

# touch 

- name: "Touch server.conf"
  file: path={{ splunk_conf_path }}/server.conf
        owner=splunk
        group=splunk
        mode=600 
        state=touch
  changed_when: false
