---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# available_sites

- name: "Configure server.conf [clustering] - available_sites state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=available_sites
            value="{{ splunk_server_conf.clustering.available_sites }}"
            state=present
  when: splunk_server_conf.clustering.available_sites is defined
  notify: splunk restart

- name: "Configure server.conf [clustering] - available_sites state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=available_sites
            state=absent
  when: splunk_server_conf.clustering.site_replication_factor is undefined
  notify: splunk restart

