---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# cluster_label

- name: "Configure server.conf [clustering] - cluster_label state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=cluster_label
            value="{{ splunk_cluster_label }}"
            state=present
  when: splunk_cluster_label is defined
  notify: splunk restart

- name: "Configure server.conf [clustering] - cluster_label state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=cluster_label
            state=absent
  when: splunk_cluster_label is undefined
  notify: splunk restart
