---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# mode

- name: "Configure server.conf [clustering] - mode state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=mode
            value={{ splunk_server_conf.clustering.mode }}
            state=present
  when: splunk_server_conf.clustering.mode is defined
  notify: splunk restart

- name: "Configure server.conf [clustering] - mode state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=mode
            state=absent
  when: splunk_server_conf.clustering.mode is undefined or
        splunk_server_conf.clustering.mode == "disabled"
  notify: splunk restart

