---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

#  multisite

- name: "Configure server.conf [clustering] - multisite state=present" 
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=multisite
            value={{ splunk_server_conf.clustering.multisite }}
            state=present
  when: splunk_server_conf.clustering is defined and 
        (splunk_server_conf.clustering.multisite is defined or
        splunk_server_conf.clustering.multisite == true)
  notify: splunk restart

- name: "Configure server.conf [clustering] - available_sites state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=available_sites
            value={{ splunk_server_conf.clustering.available_sites }}
            state=present
  when: 
    - splunk_server_conf.clustering is defined
    - splunk_server_conf.clustering.available_sites is defined
    - splunk_server_conf.clustering.mode is defined and splunk_server_conf.clustering.mode == "master"
  notify: splunk restart

- name: "Configure server.conf [clustering] - multisite state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=multisite
            state=absent
  when: splunk_server_conf.clustering.multisite is undefined or
        splunk_server_conf.clustering.multisite != true
  notify: splunk restart

- name: "Configure server.conf [clustering] - available_sites state=absent"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=available_sites
            state=absent
  when: 
    - splunk_server_conf.clustering is defined
    - splunk_server_conf.clustering.available_sites is not defined
  notify: splunk restart
