---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# replication_factor

- name: "Configure server.conf [clustering] - replication_factor state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=replication_factor
            value={{ splunk_server_conf.clustering.replication_factor }}
            state=present
  when: 
    - splunk_server_conf.clustering.mode is defined
    - splunk_server_conf.clustering.replication_factor is defined
  notify: splunk restart

- name: "Configure server.conf [clustering] - site_replication_factor state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=site_replication_factor
            value={{ splunk_server_conf.clustering.site_replication_factor }}
            state=present
  when: 
    - splunk_server_conf.clustering.mode is defined
    - splunk_server_conf.clustering.multisite is defined and splunk_server_conf.clustering.multisite == True
    - splunk_server_conf.clustering.site_replication_factor is defined
  notify: splunk restart

- name: "Configure server.conf [clustering] - replication_factor state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=replication_factor
            state=absent
  when: 
    - splunk_server_conf.clustering.mode is defined
    - splunk_server_conf.clustering.mode == "slave"
    - (splunk_server_conf.clustering.replication_factor is undefined or splunk_server_conf.clustering.replication_factor == 3)
  notify: splunk restart
