---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# search_factor

- name: "Configure server.conf [clustering] - search_factor state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=search_factor
            value={{ splunk_server_conf.clustering.search_factor }}
            state=present
  when: splunk_server_conf.clustering.search_factor is defined
  notify: splunk restart

- name: "Configure server.conf [clustering] - site_search_factor state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=site_search_factor
            value={{ splunk_server_conf.clustering.site_search_factor }}
            state=present
  when: 
    - splunk_server_conf.clustering.site_search_factor is defined
    - splunk_server_conf.clustering.multisite is defined and splunk_server_conf.clustering.multisite == True
  notify: splunk restart

- name: "Configure server.conf [clustering] - search_factor state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=search_factor
            state=absent
  when: splunk_server_conf.clustering.search_factor is undefined or
        splunk_server_conf.clustering.search_factor == 2
  notify: splunk restart

