---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [sslConfig]
#####################################################################################################################

# sslKeysfilePassword

- name: "Configure server.conf [sslConfig] - sslKeysfilePassword state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=sslConfig
            option=sslKeysfilePassword
            value={{ splunk_server_conf.sslConfig.sslKeysfilePassword }}
            state=present
  when: splunk_server_conf.sslConfig.sslKeysfilePassword is defined
  notify: splunk restart

- name: "Configure server.conf [sslConfig] - sslKeysfilePassword state=absent"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=sslConfig
            option=sslKeysfilePassword
            state=absent
  when: splunk_server_conf.sslConfig.sslKeysfilePassword is undefined
  notify: splunk restart

