---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [sslConfig]
#####################################################################################################################

# sslKeysfilePassword

- name: "Configure server.conf [sslConfig] - sslPassword state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=sslConfig
            option=sslPassword
            value={{ splunk_server_conf.sslConfig.sslPassword }}
            state=present
  when: splunk_server_conf.sslConfig.sslPassword is defined
  notify: splunk restart

- name: "Configure server.conf [sslConfig] - sslPassword state=absent"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=sslConfig
            option=sslPassword
            state=absent
  when: splunk_server_conf.sslConfig.sslPassword is undefined
  notify: splunk restart

