---
#####################################################################################################################
# Configurations for Splunk inputs.conf
#####################################################################################################################

#####################################################################################################################
# [SSL]
#####################################################################################################################

# rootCA

- name: "Configure inputs.conf: Set rootCA"
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL
            option=rootCA 
            value={{ splunk_inputs_conf.SSL.rootCA }}
            state=present
  when: splunk_inputs_conf.SSL.rootCA is defined
  notify: splunk restart

- name: "Configure inputs.conf: Unset rootCA (default)"
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL 
            option=rootCA
            state=absent
  when: splunk_inputs_conf.SSL.rootCA is undefined
  notify: splunk restart
