---
#####################################################################################################################
# Configurations for Splunk inputs.conf
#####################################################################################################################

#####################################################################################################################
# [SSL]
#####################################################################################################################

# serverCert

- name: "Configure inputs.conf: Set serverCert"
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL 
            option=serverCert
            value={{ splunk_inputs_conf.SSL.serverCert }}
            state=present
  when: splunk_inputs_conf.SSL.serverCert is defined
  notify: splunk restart

- name: "Configure inputs.conf: Unset serverCert (default)"
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL 
            option=serverCert
            state=absent
  when: splunk_inputs_conf.SSL.serverCert is undefined
  notify: splunk restart
