---
# do not use copy due to its limitations
# copy facility does not scale to lots of files
- name: Backup the current splunk dir
  become: yes
  become_user: root
  synchronize:  archive=yes
                compress=no
                src="{{ splunk_installation.remote_package_temp_path }}/{{ splunk_installation.package_file }}"
                dest={{ splunk_installation.remote_backup_path }}

