---
- name: shelper start
  shell: "{{ shelper_installation.shelper_path }}/shelperstart --accept-license --answer-yes"

- name: shelper stop
  shell: "{{ shelper_installation.shelper_path }}/shelperstop"

- name: shelper restart
  shell: "{{ shelper_installation.shelper_path }}/shelperrestart --accept-license --answer-yes"
        
- name: shelper reload deploy-server
  shell: "{{ shelper_installation.shelper_path }}/shelperdsreload --batch -auth {{ splunk_user }}:{{ splunk_password }}"
  when: inventory_hostname in groups['deploymentserver']

- name: shelper reload all
  shell: "{{ shelper_installation.shelper_path }}/shelperreload all --batch -auth {{ splunk_user }}:{{ splunk_password }}"

- name: shelper apply cluster-bundle
  shell: "{{ shelper_installation.shelper_path }}/shelpercmapply --batch -auth {{ splunk_user }}:{{ splunk_password }}"
  when: inventory_hostname in groups['masternode']

- name: shelper apply shcluster-bundle
  shell: "{{ shelper_installation.shelper_path }}/shelper apply shcluster-bundle -target https://{{ groups['shcmember'][0] }}:8089 --answer-yes -auth {{ splunk_user }}:{{ splunk_password }}"
  when: inventory_hostname in groups['deployer']
