---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [general]
#####################################################################################################################

# site

- name: "Configure server.conf [general] - site state=present (dynamic)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=general
            option=site
            value={{ hostvars[inventory_hostname].splunk_site }}
            state=present
  when: splunk_server_conf.general.site is defined and
        splunk_server_conf.general.site == "dynamic"
  notify: splunk restart

- name: "Configure server.conf [general] - site state=present (static)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=general
            option=site
            value={{ splunk_server_conf.general.site }}
            state=present
  when: splunk_server_conf.general.site is defined and
        splunk_server_conf.general.site != "dynamic"
  notify: splunk restart

- name: "Configure server.conf [general] - site state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=general
            option=site
            state=absent
  when: splunk_server_conf.general.site is undefined
  notify: splunk restart
