---
#####################################################################################################################
# Configurations for Splunk web.conf
#####################################################################################################################

#####################################################################################################################
# [settings]
#####################################################################################################################

# enableSplunkWebSSL

- name: "Configure web.conf [settings] - enableSplunkWebSSL state=present"
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings option=enableSplunkWebSSL 
            value={{ splunk_web_conf.settings.enableSplunkWebSSL }}
            state=present
  when: splunk_web_conf.settings.enableSplunkWebSSL is defined and
        splunk_web_conf.settings.enableSplunkWebSSL == true
  notify: splunk restart

- name: "Configure web.conf [settings] - enableSplunkWebSSL state=absent (default)"
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=enableSplunkWebSSL
            state=absent
  when:  splunk_web_conf.settings.enableSplunkWebSSL is undefined or 
         splunk_web_conf.settings.enableSplunkWebSSL == false
  notify: splunk restart
