---
#####################################################################################################################
# Configurations for Splunk web.conf
#####################################################################################################################

#####################################################################################################################
# [settings]
#####################################################################################################################

# updateCheckerBaseURL

- name: "Configure web.conf [settings] - updateCheckerBaseURL state=present"
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=updateCheckerBaseURL
            value={{ splunk_web_conf.settings.updateCheckerBaseURL }}
            state=present
  when: splunk_web_conf.settings.updateCheckerBaseURL is defined and 
        splunk_web_conf.settings.updateCheckerBaseURL != "http://quickdraw.Splunk.com/js/"
  notify: splunk restart

- name: "Configure web.conf [settings] - unset updateCheckerBaseURL state=absent (default)"
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=updateCheckerBaseURL
            state=absent
  when: splunk_web_conf.settings.updateCheckerBaseURL is undefined or 
        splunk_web_conf.settings.updateCheckerBaseURL == "http://quickdraw.Splunk.com/js/"
  notify: splunk restart
