---
#####################################################################################################################
# Configurations for Splunk web.conf
#####################################################################################################################

# touch

- name: "Touch web.conf"
  file: path={{ splunk_conf_path }}/web.conf
        owner=splunk
        group=splunk
        mode=600
        state=touch
  changed_when: false
