---
- include: update.yml
  when: system_yum.upgrade_system is defined and system_yum.upgrade_system == True

- include: add_elrepo.yml
  when: system_yum.elrepo.enabled

- include: install_elrepo_kernel.yml
  when: 'system_yum.elrepo.kernel.setup == "yes"'
