---
- name: Install Splunk package from rpm
  yum: name="{{ splunk_installation.remote_package_temp_path }}/{{ splunk_installation.package_file }}" 
       state=present
  when: splunk_installation.package_format == "rpm"

- name: Install Splunk package from tgz
  unarchive: src="{{ splunk_installation.remote_package_temp_path }}/{{ splunk_installation.package_file }}"
             dest=/opt
             copy=no
  when:  splunk_installation.package_format == "tgz"

- name: Remove temporary Splunk package
  command: rm "{{ splunk_installation.remote_package_temp_path }}/{{ splunk_installation.package_file }}"
  when: splunk_installation.delete_package_after_install != false

- name: Set permissions for $SPLUNK_HOME 
  file: path="{{ splunk_installation.splunk_home_path }}" 
        owner="{{ splunk_install_user }}"
        group="{{ splunk_install_group }}"
        recurse=yes
  when: splunk_installation.package_format == "tgz"

- name: Set directory permissions for splunk
  file: path={{ splunk_installation.splunk_home_path }}/
        mode=0750
