---
- include: sys_check.yml

- include: prepare_splunk.yml
  when: splunk_upgrade == False

- include: operation_mode.yml

- include: splunk_stop.yml
  when: splunk_upgrade == True

- include: install_splunk.yml

- include: set_splunk_secret.yml
  when: splunk_upgrade == False

- include: enable_boot_start_splunk.yml

- include: change_default_password.yml
  when: splunk_upgrade == False

- include: add_authorized_key.yml
  when: splunk_upgrade == False

- include: firewalld_open_splunkports.yml
  when: splunk_upgrade == False

- include: splunk_startstop.yml
  when: splunk_upgrade == False

- include: fetch_distserverkeys.yml
  when: splunk_upgrade == False

- include: optimize_tuned.yml
  when: 
    - splunk_optimize.tuned is defined
    - splunk_optimize.tuned == True

- include: optimize_initd.yml
  when: 
    - splunk_optimize.initd is defined
    - splunk_optimize.initd == True

- include: optimize_selinux.yml
  when: 
    - splunk_optimize.selinux is defined

- include: set_perms.yml

- include: splunk_start.yml
  when:
    - splpeernode.stdout != "slave" 
    #- splunk_upgrade == True

