---
- name: Import splunk checks
  import_tasks: splunk_checks.yml

# check for existence of splunk bin file
- stat: path="{{ splunk_installation.splunk_home_path }}/bin/splunk"
  register: splunkbin
  failed_when: splunkbin.stat.exists != True

- name: systemctl reload
  shell: systemctl daemon-reload
  ignore_errors: yes
 
- name: Start Splunk by service
  import_tasks: splunk_service_start.yml 
 
#- name: Start Splunk by binary
#  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk start {{ splunk_installation.splunk_args_noninteractive }}"
#  async: 1800
#  poll: 0
#  become: yes
#  become_user: "{{ splunk_install_user }}"
#  register: splunk_started_by_bin
#  when:
#        - splunkbin is defined and splunkbin.stat.exists == True

#- debug: msg="{{ splunk_restate }} . {{ splunk_stopped_by_bin}} ."

#- name: ... is Splunk by bin started?
#  async_status: jid={{ splunk_started_by_bin.ansible_job_id }}
#  register: splunk_bin_started_result
#  until: splunk_bin_started_result.finished
#  retries: 360
#  become: yes
#  become_user: "{{ splunk_install_user }}"
#  when:
#        - splunk_started_by_bin.changed is defined and splunk_started_by_bin.changed == True

# ensure splunk is REALLY running ! Do not rely on init, systemd etc!!
- name: Re-Check Splunk Status
  shell: "sleep 10s && ps aux |egrep -v '(ssh|grep|tail|less|vim|vi|patrol)' |grep splunkd"
  register: splunk_laststate
  failed_when: splunk_laststate.rc != 0

